# Simple POS — Public Shopify App

client_id = "e6a8aed068a867edeeabdefa7a47ec68"
application_url = "https://simple-pos-production-36de.up.railway.app"
embedded = true
name = "Simple POS"

[access_scopes]
scopes = "write_products,read_products,write_metaobjects,write_metaobject_definitions,write_draft_orders,read_orders,write_orders,write_customers,read_customers,read_inventory,write_inventory,read_locations"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://simple-pos-production-36de.up.railway.app/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true